name: release_to_npm
on:
  release:
    types: [ created ]

jobs:

  sync_badges:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      
      - run: |
          rm -rf .ci_badges
          node ./cli.js
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .ci_badges
          git commit -m "[CI:deploy] sync_badges job"

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_and_publish:
    runs-on: ubuntu-18.04
    needs: sync_badges
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

     - uses: actions/setup-node@v1
       with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

     - run: |
          yarn build
          npm publish --access public
       env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}